---
layout: default
title: How to contribute
---

# How to Contribute
The content of this website is Eric C. Anderson's first attempt at teaching
a course in which almost all of the content is written using Rmarkdown. Currently
all the sources in the rep-res-course repository are built on my local machine using Jekyll (because GitHub does
not support custom Jekyll plugins) and then I copy the results (in the _site directory) to the
gh-pages branch of my rep-res-web repository on GitHub where it gets served up at
http://eriqande.github.io/rep-res-web/

If you have recommended edits, the best way to get them to me is to:

1. Have a GitHub account.
2. Click on the "Edit this page" button.

Doing so will give you a fork of the rep-res-course repository, and you can
edit the raw Rmarkdown source that produced the page and send me a pull request.
Understand that any contributions you make that are pulled into the project
will enter the public domain.

You can also provide comments on most pages through the Disqus comments system.

I welcome any recommendations from simple typo-fixes to suggestions on how my R code 
can be improved and suggestions
on how this material could be taught more effectively.   I would particularly appreciate
it if you were to send me any fun "homework exercises" that would be beneficial for students
learning this material.

If you have any questions, feel free to raise them in the pull request,
send me [an email](mailto:eric.anderson@noaa.gov) or post a comment in the discussion at the 
bottom of the page you want to comment on.
